# Generated by Django 6.0.7 on 2026-07-27 14:32

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
        ('assignments', '0003_subject_assignment_matched_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='assignments.subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[accounts.models.validate_admission_year]),
        ),
    ]
