# Generated by Django 6.0.7 on 2026-07-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_semester_remove_user_subject_and_more'),
        ('assignments', '0004_alter_assignment_matched_assignment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='level',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master')], default='bachelor', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'subject', 'semester', 'level')},
        ),
    ]
