# Generated by Django 6.0.7 on 2026-08-07 15:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_first_login_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_year',
            field=models.PositiveIntegerField(validators=[accounts.models.validate_admission_year]),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='students/'),
        ),
    ]
