# Generated by Django 6.0.7 on 2026-08-14 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_admission_year_alter_user_photo'),
        ('assignments', '0010_department_level_teachertask_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassignment',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='assignments.level'),
        ),
    ]
