# Generated by Django 6.0.7 on 2026-08-15 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_teacherassignment_level'),
        ('assignments', '0011_alter_assignment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='assignments.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='assignments.level'),
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
