# Generated by Django 6.0.7 on 2026-08-15 07:36

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_department_user_level_user_semester'),
        ('assignments', '0014_alter_subject_options_alter_assignment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='semester',
        ),
        migrations.AddField(
            model_name='user',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailverificationotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='level',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[accounts.models.validate_admission_year]),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='assignments.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='assignments.level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
