# Generated by Django 6.0.7 on 2026-07-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='semester',
            field=models.PositiveIntegerField(),
        ),
    ]
