# Generated by Django 6.0.7 on 2026-07-28 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_subject_assignment_matched_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='matched_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_assignments', to='assignments.assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assignments.subject'),
        ),
    ]
