# Generated by Django 6.0.7 on 2026-07-29 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='analysis_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='analysis_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='matched_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_with', to='assignments.assignment'),
        ),
        migrations.DeleteModel(
            name='AssignmentHistory',
        ),
    ]
