# Generated by Django 6.0.7 on 2026-07-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignment_analysis_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='analysis_completed',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='analysis_error',
        ),
    ]
