# Generated by Django 6.0.7 on 2026-08-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_remove_assignment_analysis_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='similarity_percentage',
            field=models.CharField(default='0%', max_length=50),
        ),
    ]
