# Generated by Django 6.0.7 on 2026-08-13 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_alter_assignment_similarity_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='resubmission_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_attempt',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending_review', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resubmission_required', 'Resubmission Required'), ('final_rejected', 'Final Rejected'), ('overdue', 'Overdue')], default='pending_review', max_length=30),
        ),
        migrations.CreateModel(
            name='TeacherTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assignments.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.teachertask'),
        ),
    ]
