# Generated by Django 6.0.7 on 2026-08-15 05:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_alter_assignment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertask',
            name='show_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
