# Generated by Django 6.0.7 on 2026-08-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_alter_subject_options_alter_assignment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='matching_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
